name: qhala
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  logger: ^1.0.0
  lottie: ^1.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/loading.json
    - assets/lottie/error.json
